#!/usr/bin/env bash
# export GTK_IM_MODULE=xim
# export XMODIFIERS=@im=ibus
# export QT_IM_MODULE=xim

set -eu

mkdir -p "$HOME/Downloads/ffs"

xdg_cache="${XDG_CACHE_HOME-$HOME/.cache}"
xdg_data="${XDG_DATA_HOME-$HOME/.local/share}"
xdg_runtime="${XDG_RUNTIME_DIR-/run/user/$(id -u)}"

env -i bwrap \
    --symlink usr/lib /lib \
    --symlink usr/lib64 /lib64 \
	--ro-bind /tmp/.X11-unix /tmp/.X11-unix \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/lib64 /usr/lib64 \
    --ro-bind /usr/share/applications /usr/share/applications \
    --ro-bind /usr/share/ca-certificates /usr/share/ca-certificates \
	--ro-bind /usr/share/mime /usr/share/mime \
    --ro-bind /usr/share/fonts /usr/share/fonts \
    --ro-bind /usr/share/glib-2.0 /usr/share/glib-2.0 \
    --ro-bind /usr/share/glvnd /usr/share/glvnd \
    --ro-bind /usr/share/icons /usr/share/icons \
    --ro-bind /usr/share/libdrm /usr/share/libdrm \
    --ro-bind /usr/share/mime /usr/share/mime \
    --ro-bind /usr/share/X11/xkb /usr/share/X11/xkb \
    --ro-bind /usr/share/icons /usr/share/icons \
    --ro-bind /usr/share/mime /usr/share/mime \
    --ro-bind /etc/fonts /etc/fonts \
	--ro-bind /etc/opensc.conf /etc/opensc.conf \
    --ro-bind /etc/resolv.conf /etc/resolv.conf \
    --proc /proc --dev /dev \
    --dev-bind /dev/dri /dev/dri \
    --ro-bind /sys/dev/char /sys/dev/char \
    --ro-bind /sys/devices/pci0000:00 /sys/devices/pci0000:00 \
    --ro-bind $HOME/box/machine-id /etc/machine-id \
    --bind $HOME/box/.mozilla /home/J31/.mozilla \
    --unshare-all --share-net \
    --hostname J31 \
    --setenv /usr/lib64/firefox/ /usr/lib4/firefox \
    --setenv HOME /home/J31 \
    --setenv SHELL /sbin/nologin \
    --setenv GTK_THEME Adwaita:dark \
    --setenv MOZ_ENABLE_WAYLAND 1 \
    --new-session --die-with-parent --cap-drop ALL \
    --ro-bind "/run/dbus" "/run/dbus" \
    --ro-bind "$xdg_runtime/wayland-1" "$xdg_runtime/wayland-1" \
    /usr/lib64/firefox/firefox-bin "$@" --no-remote -P \

# vi:ft=sh
